import LuisDev from '../assets/LuisDev.png'
import reactSvg from '../assets/circle/react.svg'
import typescript from '../assets/circle/typescript.svg'
import cypress from '../assets/circle/cypress.svg'
import cssSvg from '../assets/circle/css.svg'
import node from '../assets/circle/nodejs.svg'
import tailwind from '../assets/circle/tailwind.svg'
import html from '../assets/circle/html.svg'
import javascript from '../assets/circle/javascript.svg'
import mongo from '../assets/circle/mongo.svg'
import mysql from '../assets/circle/mysql.svg'
import vite from '../assets/circle/vite.svg'
import firebase from '../assets/circle/firebase.svg'
import github from '../assets/circle/github.svg'
import sass from '../assets/circle/sass.svg'
import nextjs from '../assets/circle/nextjs.svg'
import materialUi from '../assets/circle/materialUi.svg'
import php from '../assets/circle/php.svg'
import laravel from '../assets/circle/laravel.svg'
import Ccharp from '../assets/circle/Ccharp.svg'
export const imagesImport = () => {
    return { LuisDev, reactSvg, typescript, cypress, cssSvg, node, tailwind, html, javascript, mongo, mysql, vite, firebase, github, sass, nextjs, materialUi, php, laravel, Ccharp }
}